wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.6.5
batch_size:
  desc: null
  value: 22.04012522309925
epochs:
  desc: null
  value: 3.3403511761978284
learning_rate:
  desc: null
  value: -0.6289846215689825
