wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.6.5
batch_size:
  desc: null
  value: 289.97251587783245
epochs:
  desc: null
  value: 675.0988754876336
learning_rate:
  desc: null
  value: -0.16796312627301152
