wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.6.5
batch_size:
  desc: null
  value: 34.27031619771228
epochs:
  desc: null
  value: 3.7135666198863864
learning_rate:
  desc: null
  value: 0.45346657726298356
