wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.6.5
batch_size:
  desc: null
  value: 334.57430164815554
epochs:
  desc: null
  value: 905.7900059311355
learning_rate:
  desc: null
  value: 0.9079741727808801
