wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.6.5
batch_size:
  desc: null
  value: 90.28215975119905
epochs:
  desc: null
  value: 341.7651621142948
learning_rate:
  desc: null
  value: 0.1319028449496636
