wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    framework: tensorflow
    is_jupyter_run: true
    python_version: 3.6.5
batch_size:
  desc: null
  value: 10
epochs:
  desc: null
  value: 2
seed:
  desc: null
  value: 42
