wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.6.5
batch_size:
  desc: null
  value: 342.6554554958013
epochs:
  desc: null
  value: 911.2742139201309
learning_rate:
  desc: null
  value: 0.1721797367330594
