wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.6.5
batch_size:
  desc: null
  value: 200.43437809454045
epochs:
  desc: null
  value: 669.0930410884598
learning_rate:
  desc: null
  value: -0.015914221334234674
