wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.6.5
batch_size:
  desc: null
  value: 157.1195316987936
epochs:
  desc: null
  value: 969.7621009095162
learning_rate:
  desc: null
  value: -0.23670271472876048
