wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.6.5
batch_size:
  desc: null
  value: 16.236354102989697
epochs:
  desc: null
  value: 6.115494520862195
learning_rate:
  desc: null
  value: -0.9814794176401515
