wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.6.5
batch_size:
  desc: null
  value: 349.54499392258106
epochs:
  desc: null
  value: 296.29060776691995
learning_rate:
  desc: null
  value: -0.6719247884708163
