wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.18
    is_jupyter_run: true
    python_version: 3.6.5
batch_size:
  desc: null
  value: 29.88910906273523
epochs:
  desc: null
  value: 9.82021554969241
learning_rate:
  desc: null
  value: -1.05346616885208
